version: '3.8'

services:
  web:
    build:
      context: django_weather_reminder
      dockerfile: src/Dockerfile.prod
    image: vyacheslavseregin21/web:1.0
    command: gunicorn django_weather_reminder.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/django_weather_reminder/weather_app/staticfiles
      - media_volume:/home/django_weather_reminder/weather_app/media
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis
      - celery-beat
  worker:
    restart: always
    build:
      context: django_weather_reminder
      dockerfile: src/Dockerfile_worker
    command: celery -A django_weather_reminder worker -l info --time-limit 3600
    volumes:
      - static_volume:/home/django_weather_reminder/weather_app/staticfiles
      - media_volume:/home/django_weather_reminder/weather_app/media
    env_file:
      - .env.prod
    depends_on:
      - redis
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db
  nginx:
    build: nginx
    image: vyacheslavseregin21/nginx:1.0
    volumes:
      - static_volume:/home/django_weather_reminder/weather_app/staticfiles
      - media_volume:/home/django_weather_reminder/weather_app/media
    ports:
      - 1337:80
    depends_on:
      - web
  redis:
    image: redis:alpine
    restart: always
    expose:
      - 6379
  celery-beat:
    build:
      context: django_weather_reminder
      dockerfile: src/Dockerfile_celerybeat
    command: celery -A django_weather_reminder beat -l info
    env_file:
      - .env.prod
    depends_on:
      - worker
      - redis
      - db
    restart: always
    volumes:
      - static_volume:/home/django_weather_reminder/weather_app/staticfiles
      - media_volume:/home/django_weather_reminder/weather_app/media
  flower:
    build:
      context: django_weather_reminder
      dockerfile: src/Dockerfile_worker
    command: celery -A django_weather_reminder flower
    volumes:
      - static_volume:/home/django_weather_reminder/weather_app/staticfiles
      - media_volume:/home/django_weather_reminder/weather_app/media
    env_file:
      - .env.prod
    depends_on:
      - redis
    ports:
      - "5555:5555"

volumes:
  postgres_data:
  static_volume:
  media_volume: