version: '3.8'

services:
  worker:
    restart: always
    build:
      context: django_weather_reminder
      dockerfile: src/Dockerfile_worker
    command: celery -A django_weather_reminder worker -l info && celery -A django_weather_reminder beat
    volumes:
      - static_volume:/home/django_weather_reminder/weather_app/staticfiles
      - media_volume:/home/django_weather_reminder/weather_app/media
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis
  web:
    build:
      context: django_weather_reminder
      dockerfile: src/Dockerfile.prod
    image: vyacheslavseregin21/web:1.0
    command: gunicorn django_weather_reminder.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/django_weather_reminder/weather_app/staticfiles
      - media_volume:/home/django_weather_reminder/weather_app/media
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db
  nginx:
    build: nginx
    image: vyacheslavseregin21/nginx:1.0
    volumes:
      - static_volume:/home/django_weather_reminder/weather_app/staticfiles
      - media_volume:/home/django_weather_reminder/weather_app/media
    ports:
      - 1337:80
    depends_on:
      - web
  redis:
    image: redis:7-alpine
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume:
  #  celery-beat:
  #    build: .
  #    command: celery -A proj beat -l info
  #    volumes:
  #      - static_volume:/home/django_weather_reminder/weather_app/staticfiles
  #      - media_volume:/home/django_weather_reminder/weather_app/media
  #    depends_on:
  #      - db
  #      - redis



#version: '3.8'
#
#services:
#  web:
#    build:
#      context: django_weather_reminder
#      dockerfile: src/Dockerfile.prod
#    image: vyacheslavseregin21/web:1.0
#    command: gunicorn django_weather_reminder.wsgi:application --bind 0.0.0.0:8000
#    volumes:
#      - static_volume:/home/django_weather_reminder/weather_app/staticfiles
#      - media_volume:/home/django_weather_reminder/weather_app/media
#    expose:
#      - 8000
#    env_file:
#      - .env.prod
#    depends_on:
#      - db
#  worker:
#    restart: always
#    build:
#      context: django_weather_reminder
#      dockerfile: src/Dockerfile.prod
#    command: celery -A django_weather_reminder worker -l info
#    volumes:
#      - static_volume:/home/django_weather_reminder/weather_app/staticfiles
#      - media_volume:/home/django_weather_reminder/weather_app/media
#    env_file:
#      - .env.prod
#    depends_on:
#      - db
#      - redis
#  db:
#    image: postgres:13.0-alpine
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#    env_file:
#      - .env.prod.db
#  nginx:
#    build: nginx
#    image: vyacheslavseregin21/nginx:1.0
#    volumes:
#      - static_volume:/home/django_weather_reminder/weather_app/staticfiles
#      - media_volume:/home/django_weather_reminder/weather_app/media
#    ports:
#      - 1337:80
#    depends_on:
#      - web
#  redis:
#    image: redis:7-alpine
#    restart: always
#
#volumes:
#  postgres_data:
#  static_volume:
#  media_volume:
#




