# Generated by Django 4.2.4 on 2023-08-28 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'city',
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=256)),
                ('temp', models.FloatField()),
                ('pressure', models.FloatField()),
                ('humidity', models.FloatField()),
                ('clouds', models.CharField(max_length=256)),
                ('wind_speed', models.FloatField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='weather_app.city')),
            ],
            options={
                'verbose_name': 'weather',
            },
        ),
        migrations.CreateModel(
            name='SubscribedCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_notifications', models.IntegerField()),
                ('last_run_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_subs', to='weather_app.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'subscribed_city',
            },
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['name'], name='weather_app_name_053612_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subscribedcity',
            unique_together={('user', 'city')},
        ),
    ]
